let inc = 0

export const types = Object.freeze({
	UNKNOWN: inc++,
	COMMENT: inc++,
	SPACE: inc++,
	TAB: inc++,
	LABEL: inc++,
	FUNCTION: inc++,
	STRING: inc++,
	VALUE: inc++,
	EQUAL: inc++,
	NEWLINE: inc++,
	LABEL_VALUE: inc++,
	CONST: inc++,
	NUMBER: inc++,
	HEX_VALUE: inc++,
	INSTRUCTION: inc++,
	BIN_VALUE: inc++,
	OPEN_BRACKET: inc++,
	CLOSE_BRACKET: inc++,
	COMMA: inc++,
	LOW_BYTE: inc++,
	HI_BYTE: inc++,
	X: inc++,
	Y: inc++,
	CONST_VALUE: inc++,
})

export const valueType = Object.freeze({
	INDIRECT: inc++,
	INDIRECT_X: inc++,
	INDIRECT_Y: inc++,
	IND_ZERO_PAGE: inc++,
	LABEL_INDIRECT: inc++,
	LABEL_INDIRECT_X: inc++,
	LABEL_INDIRECT_Y: inc++,
	IMMEDIATE: inc++,
	ABSOLUTE: inc++,
	ABSOLUTE_X: inc++,
	ABSOLUTE_Y: inc++,
	ZERO_PAGE: inc++,
	ZERO_PAGE_X: inc++,
	ZERO_PAGE_Y: inc++,
	LABEL_ABSOLUTE: inc++,
	LABEL_ABSOLUTE_X: inc++,
	LABEL_ABSOLUTE_Y: inc++,
	CONST: inc++,
})